// <auto-generated />
using System;
using HighPerformance.Ingest.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace HighPerformance.Ingest.Infrastructure.Persistence.Migrations;

[DbContext(typeof(AppDbContext))]
[Migration("202603260001_RemoveProductos")]
partial class RemoveProductos
{
}
